-- Disable RLS on CVs tables to allow unrestricted access
ALTER TABLE "CVs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CVs_duplicate" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Jobs_CVs" DISABLE ROW LEVEL SECURITY;