// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tifgdxfceojbrmprngvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZmdkeGZjZW9qYnJtcHJuZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDAxNzIsImV4cCI6MjA2OTg3NjE3Mn0.tVi5cM8Exu_rA0iHLqih8INU98C8X-m-MKBXW_4f5lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});